# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_loading_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Camera_loading_gui(object):
    def setupUi(self, Camera_loading_gui):
        Camera_loading_gui.setObjectName("Camera_loading_gui")
        Camera_loading_gui.resize(827, 703)
        self.centralWidget = QtWidgets.QWidget(Camera_loading_gui)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 460, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 1, 1, 1)
        self.comboBox_image_num = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_image_num.setObjectName("comboBox_image_num")
        self.gridLayout.addWidget(self.comboBox_image_num, 4, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 90, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 3, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_Load = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Load.sizePolicy().hasHeightForWidth())
        self.pushButton_Load.setSizePolicy(sizePolicy)
        self.pushButton_Load.setObjectName("pushButton_Load")
        self.gridLayout_2.addWidget(self.pushButton_Load, 2, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 3, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 1, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 0, 1, 1)
        self.lineEdit_Browse = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Browse.setObjectName("lineEdit_Browse")
        self.gridLayout_2.addWidget(self.lineEdit_Browse, 2, 1, 1, 1)
        self.pushButton_Browse = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Browse.setObjectName("pushButton_Browse")
        self.gridLayout_2.addWidget(self.pushButton_Browse, 2, 0, 1, 1)
        self.checkBox_show_max = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_show_max.setObjectName("checkBox_show_max")
        self.gridLayout_2.addWidget(self.checkBox_show_max, 1, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 1, 1, 3)
        self.gridLayout_pic = QtWidgets.QGridLayout()
        self.gridLayout_pic.setSpacing(6)
        self.gridLayout_pic.setObjectName("gridLayout_pic")
        self.gridLayout.addLayout(self.gridLayout_pic, 5, 1, 1, 3)
        self.pushButton_show = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_show.setFont(font)
        self.pushButton_show.setObjectName("pushButton_show")
        self.gridLayout.addWidget(self.pushButton_show, 4, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        Camera_loading_gui.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Camera_loading_gui)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 827, 21))
        self.menuBar.setObjectName("menuBar")
        Camera_loading_gui.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(Camera_loading_gui)
        self.mainToolBar.setObjectName("mainToolBar")
        Camera_loading_gui.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(Camera_loading_gui)
        self.statusBar.setObjectName("statusBar")
        Camera_loading_gui.setStatusBar(self.statusBar)

        self.retranslateUi(Camera_loading_gui)
        QtCore.QMetaObject.connectSlotsByName(Camera_loading_gui)

    def retranslateUi(self, Camera_loading_gui):
        _translate = QtCore.QCoreApplication.translate
        Camera_loading_gui.setWindowTitle(_translate("Camera_loading_gui", "Camera_loading_gui"))
        self.label.setText(_translate("Camera_loading_gui", "Image:"))
        self.groupBox.setTitle(_translate("Camera_loading_gui", "Load"))
        self.pushButton_Load.setText(_translate("Camera_loading_gui", "Load"))
        self.pushButton_Browse.setText(_translate("Camera_loading_gui", "Browse"))
        self.checkBox_show_max.setText(_translate("Camera_loading_gui", "Show Max pixel"))
        self.pushButton_show.setText(_translate("Camera_loading_gui", "Show"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Camera_loading_gui = QtWidgets.QMainWindow()
    ui = Ui_Camera_loading_gui()
    ui.setupUi(Camera_loading_gui)
    Camera_loading_gui.show()
    sys.exit(app.exec_())
